### ISSUE TITLE
Bangumi API 中 Cookies 行为（以及用户信息 API）

### ISSUE THREAD

**Issue by CNA-Bld** [jabbany/dhufufu#7]
`chii_sid` 似乎并不影响请求，inTouch 的 API 请求中不会携带此 Cookie。
`__cfduid` 是 CloudFlare CDN 产生的 Cookie，不影响请求。

以及 `source` 参数必须为 `onAir` 的地方使用 `intouch` 也可以。

另外还有一个不需要登录获取用户信息的 API，位置在
[GET] /user/{$UID/USERNAME}

返回的信息和 /auth 类似：

```
{
    id: 用户UID
    url: 用户空间URL
    username: 用户名（部分用户与 UID 相同）
    nickname: 用户昵称
    avatar:{
        large: 头像、大
        medium: 头像、中
        small: 头像、小
    }
    sign: 签名
}
```

**Comment by jabbany** [comment]
bangumi在2018年推出官方API了！
集体整理古董级issue（
